# Site Settings
title: Emanuel Maracajá
url: 'https://efmaracaja.github.io'
baseurl: '/cvEN' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Emanuel Maracajá
tagline: Maîtrise en Efficacité Énergétique et Énergies Renouvelables
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: <p align="justify">Je suis passionné par le domaine de l’efficacité énergétique. Je m’intéresse aux audits énergétiques et simulations. Mon projet à la maitrise porte sur l’audit et simulation énergétique du système hydronique (refroidisseurs, chaudière et tours de refroidissement) d’un bâtiment du campus de l’ÉTS. Ce projet vise à faire le bilan énergétique, revoir les séquences de contrôle du système et proposer des mesures d’efficacité énergétique. J'ai de l'expérience dans le domaine de l'analyse des données pour la prise des décisions. Dans le contexte de la révolution numérique, la donnée est devenue un outil très puissant pour l’innovation dans le domaine de l’efficacité et aussi pour la transformation du monde. De ce fait, je m’intéresse beaucoup à la science et l’analyse des données pour la prise des décisions. J’ai de l’expérience dans ce domaine.


 </p>



#sidebar links
email: emanuel.ferreira-maracaja.1@ens.etsmtl.ca
phone: +1 (438) 345-3241
website: efmaracaja.github.io #do not add http://
linkedin: emanuel-maracaja
#github: efmaracaja
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
